package com.song.work.dao.mapper;

import com.song.work.model.Company;
import com.song.work.model.CompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	int countByExample(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	int deleteByExample(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	int deleteByPrimaryKey(Integer cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	int insert(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	int insertSelective(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	List<Company> selectByExample(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	Company selectByPrimaryKey(Integer cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Company record, @Param("example") CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	int updateByExample(@Param("record") Company record, @Param("example") CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	int updateByPrimaryKeySelective(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	int updateByPrimaryKey(Company record);

	List<Company> findAll();
}